version: "3.9"
services:
  gateway:
    image: traefik:latest
    restart: always
    command:
      - --providers.docker
      - --entryPoints.web.address=:8080
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
  backend:
    image: twaddle/api:latest
    build:
      context: .
    restart: always
    expose:
      - 3000
    volumes:
      - type: bind
        source: ./public
        target: /usr/local/bin/twaddle/api/public
        read_only: true
      - type: bind
        source: ./resources
        target: /usr/local/bin/twaddle/api/resources
        read_only: true
      - backend-uploads:/usr/local/bin/twaddle/api/uploads
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=PathPrefix(`/`)
volumes:
  backend-uploads:
