version: "3.9"
services:
  gateway:
    image: traefik:latest
    restart: always
    command:
      - --providers.docker
      - --entryPoints.web.address=:8080
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
  database:
    image: mongo:latest
    restart: always
    volumes:
      - database-datadb:/data/db
      - database-configdb:/data/configdb
    expose:
      - 27017
  cache:
    image: redis:latest
    restart: always
    volumes:
      - cache-data:/data
    expose:
      - 6379
  backend:
    image: twaddle/api:latest
    build:
      context: ../
    restart: always
    expose:
      - 3000
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://database:27017/twaddle
      CACHE_URL: redis://cache:6379/
    volumes:
      - backend-uploads:/usr/local/bin/twaddle/api/uploads
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=PathPrefix(`/`)
volumes:
  database-datadb:
  database-configdb:
  cache-data:
  backend-uploads:
